=== aleksgor/t1/test/src/test/resources/configuration/serverModel.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="serverModel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="storeModels" minOccurs="0" maxOccurs="1" type="storeModels" />
                <xs:element name="listeners" type="listeners" />
                <xs:element name="commandPlugins" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="commandPlugin" type="commandPlugin" minOccurs="1" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="servers" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="connect" minOccurs="0" maxOccurs="unbounded" type="serverConnect" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="clients" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="connect" minOccurs="0" maxOccurs="unbounded" type="clientConnect" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="dataSources" minOccurs="0" maxOccurs="1" type="dataSources" />
                <xs:element name="sessionClients" minOccurs="0" maxOccurs="1" type="sessionClients" />

                <xs:element type="xs:boolean" name="calculateStatistic" minOccurs="0" maxOccurs="1" />
                <xs:element type="xs:string" name="pluginPath" minOccurs="0" maxOccurs="1" />
                <xs:element name="saveClients" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="saveClient" minOccurs="0" maxOccurs="unbounded" type="saveClient" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="saveServers" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="saveServer" minOccurs="0" maxOccurs="unbounded" type="saveServer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element type="xs:string" name="serverName" />
                <xs:element name="sessionServer" minOccurs="0" maxOccurs="1" type="sessionServer" />
                <xs:element name="properties" maxOccurs="1" minOccurs="0" type="properties" />
                <xs:element name="sessionCallBackServer" minOccurs="0" maxOccurs="1" type="sessionCallBackServer" />
                <xs:element name="serializer" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="class" minOccurs="1" maxOccurs="1" />
                            <xs:element type="xs:string" name="serializerClass" minOccurs="1" maxOccurs="1" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="commandServer" minOccurs="0" maxOccurs="1" type="commandServer" />
                <xs:element name="managementServer" minOccurs="0" maxOccurs="1" type="managementServer" />
                <xs:element name="trustSessions" minOccurs="0" maxOccurs="1" type="xs:boolean" default="true" />
                <xs:element name="maxExecThreads" minOccurs="0" maxOccurs="1" type="xs:int" default="50" />
                <xs:element name="idGeneratorServer" minOccurs="0" maxOccurs="1" type="idGeneratorServer" />

                <xs:element name="idGeneratorClients" minOccurs="0" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="idGeneratorClient" minOccurs="0" maxOccurs="unbounded" type="idGeneratorClient" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="idGeneratorClient">
        <xs:complexContent mixed="false">
            <xs:extension base="commonClient">
                <xs:sequence>
                    <xs:element name="modelNames" minOccurs="0" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="modelName" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="idGeneratorServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer">
                <xs:sequence>
                    <xs:element name="increment" type="xs:int" minOccurs="0" maxOccurs="1" />
                    <xs:element name="timeOut" type="xs:int" minOccurs="0" maxOccurs="1" />
                    <xs:element name="modelSource" type="modelSource" minOccurs="0" maxOccurs="1" />
                    <xs:element name="invokerClass" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="modelSource">
        <xs:sequence>
            <xs:element type="entry" name="entry" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="entry">
        <xs:sequence>
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:string" name="value" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="commandPlugin">
        <xs:sequence>
            <xs:element type="xs:int" name="checkDelay" />
            <xs:element type="xs:string" name="class" />
            <xs:element type="xs:int" name="poolSize" />
            <xs:element type="xs:int" name="timeout" />
            <xs:element name="properties" maxOccurs="1" minOccurs="0" type="properties" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="storeModels">
        <xs:sequence>
            <xs:element name="storeModel" minOccurs="0" maxOccurs="unbounded" type="storeModel" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sessionClients">
        <xs:sequence>
            <xs:element name="sessionClient" minOccurs="0" maxOccurs="unbounded" type="sessionClient" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="storeModel">
        <xs:sequence>
            <xs:element type="xs:string" name="dataSource" />
            <xs:element type="xs:string" name="model" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:string" name="class" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:boolean" name="readThrough" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:boolean" name="writeThrough" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="copyCount" minOccurs="1" maxOccurs="1" />
            <xs:element name="serverType" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="CACHE" />
                        <xs:enumeration value="CACHE_MANAGER" />
                        <xs:enumeration value="CACHE_CACHE_MANAGER" />
                        <xs:enumeration value="TRANSLATOR" />
                        <xs:enumeration value="ALL" />
                    </xs:restriction>
                </xs:simpleType>

            </xs:element>
            <xs:element name="storeType" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="OBJECT" />
                        <xs:enumeration value="BYTES" />
                        <xs:enumeration value="ZIPPED_BYTES" />
                    </xs:restriction>
                </xs:simpleType>

            </xs:element>
            <xs:element name="cacheMatcher" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element type="xs:string" name="class" minOccurs="1" maxOccurs="1" />
                        <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="listeners">
        <xs:sequence>
            <xs:element name="listener" minOccurs="0" maxOccurs="unbounded" type="listener" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="listener">
        <xs:sequence>
            <xs:element type="xs:string" name="host" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:int" name="port" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="backlog" minOccurs="0" maxOccurs="1" default="1000" />
            <xs:element type="xs:int" name="minThreads" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="maxThreads" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="status" maxOccurs="1" minOccurs="0" default="0" />
            <xs:element type="xs:string" name="protocolType" maxOccurs="1" minOccurs="0" default="TCP" />
            <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="dataSources">
        <xs:sequence>
            <xs:element name="dataSource" minOccurs="0" maxOccurs="unbounded" type="dataSource" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dataSource">
        <xs:sequence>
            <xs:element type="xs:string" name="name" />
            <xs:element type="xs:string" name="class" />
            <xs:element type="xs:int" name="threads" />
            <xs:element type="xs:int" name="timeout" minOccurs="1" maxOccurs="1" />
            <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="clientConnect">
        <xs:sequence>
            <xs:element name="status" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Unknown" />
                        <xs:enumeration value="OK" />
                        <xs:enumeration value="Inaccessible" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="threads" minOccurs="1" maxOccurs="1" />

            <xs:element type="commonClient" name="managementClient" minOccurs="1" maxOccurs="1" />
            <xs:element type="listener" name="listener" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="serverConnect">
        <xs:sequence>
            <xs:element name="status" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Unknown" />
                        <xs:enumeration value="OK" />
                        <xs:enumeration value="Inaccessible" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="threads" minOccurs="1" maxOccurs="1" />

            <xs:element type="commonClient" name="managementServer" minOccurs="1" maxOccurs="1" />
            <xs:element type="listener" name="listener" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="properties">
        <xs:sequence>
            <xs:element name="entry" minOccurs="0" maxOccurs="unbounded" type="property" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="property">
        <xs:sequence>
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:string" name="value" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="commonServer">
        <xs:sequence>
            <xs:element type="xs:string" name="host" minOccurs="0" maxOccurs="1" />
            <xs:element type="xs:int" name="port" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="minThreads" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="maxThreads" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:long" name="keepAliveTime" minOccurs="1" maxOccurs="1" />
            <xs:element type="protocolType" name="protocolType" minOccurs="0" maxOccurs="1" />
            <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="commonClient">
        <xs:sequence>
            <xs:element type="xs:string" name="host" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="port" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="threads" minOccurs="1" maxOccurs="1" />
            <xs:element type="xs:int" name="timeout" minOccurs="1" maxOccurs="1" />
            <xs:element type="protocolType" name="protocolType" minOccurs="0" maxOccurs="1" />
            <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="protocolType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TCP" />
            <xs:enumeration value="UDP" />
            <xs:enumeration value="SSL" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="saveClient">
        <xs:complexContent mixed="false">
            <xs:extension base="commonClient" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="saveServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer">
                <xs:sequence>
                    <xs:element type="xs:long" name="sessionTimeout" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="sessionServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer">
                <xs:sequence>
                    <xs:element name="sessionTimeLive" type="xs:long" />
                    <xs:element name="authorizationService" type="authorizationService" minOccurs="0" maxOccurs="1" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="authorizationService">
        <xs:sequence>
            <xs:element name="clazz" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="properties" minOccurs="0" maxOccurs="1" type="properties" />
        </xs:sequence>

    </xs:complexType>

    <xs:complexType name="sessionClient">
        <xs:complexContent mixed="false">
            <xs:extension base="commonClient" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="sessionCallBackServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="commandServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="managementServer">
        <xs:complexContent mixed="false">
            <xs:extension base="commonServer" />
        </xs:complexContent>
    </xs:complexType>



</xs:schema>

=== aleksgor/t1/test/src/test/resources/configuration/hybrid/translator.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<serverModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../serverModel.xsd">
    <storeModels />
    <listeners>
        <listener>
            <host>localhost</host>
            <port>2022</port>
            <backlog>10000</backlog>
            <minThreads>7</minThreads>
            <maxThreads>7</maxThreads>
            <status>1</status>
            <properties />
        </listener>
        <listener>
            <host>localhost</host>
            <port>2032</port>
            <backlog>10000</backlog>
            <minThreads>7</minThreads>
            <maxThreads>7</maxThreads>
            <status>1</status>
            <properties />
        </listener>
    </listeners>
    <commandPlugins>
        <commandPlugin>
            <checkDelay>3000</checkDelay>
            <class>com.ag.plugin.IdGenerator</class>
            <poolSize>10</poolSize>
            <timeout>10000</timeout>
        </commandPlugin>
    </commandPlugins>
    <servers />
    <clients />
    <dataSources />
    <sessionClients />
    <calculateStatistic>true</calculateStatistic>
    <saveClients>
        <saveClient>
            <host>localhost</host>
            <port>5824</port>
            <threads>5</threads>
            <timeout>1000</timeout>
        </saveClient>
    </saveClients>
    <serverName>cacheTranslator</serverName>
    <managementServer>
        <host>localhost</host>
        <port>2042</port>
        <minThreads>10</minThreads>
        <maxThreads>20</maxThreads>
        <keepAliveTime>1000</keepAliveTime>
    </managementServer>
</serverModel>

=== aleksgor/t1/test/src/test/resources/configuration/hybrid/cacheManager.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<serverModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../serverModel.xsd">
    <storeModels>
        <storeModel>
            <dataSource>a</dataSource>
            <model>Child</model>
            <class>com.ag.cache.test.model.Child</class>
            <readThrough>true</readThrough>
            <writeThrough>true</writeThrough>
            <copyCount>2</copyCount>
            <serverType>CACHE_MANAGER</serverType>
            <storeType>BYTES</storeType>
        </storeModel>
        <storeModel>
            <dataSource>a</dataSource>
            <model>MainTestModel</model>
            <class>com.ag.cache.test.model.MainTestModel</class>
            <readThrough>true</readThrough>
            <writeThrough>true</writeThrough>
            <copyCount>2</copyCount>
            <serverType>CACHE_MANAGER</serverType>

            <storeType>BYTES</storeType>
        </storeModel>
    </storeModels>
    <listeners>
        <listener>
            <host>localhost</host>
            <port>2122</port>
            <backlog>10</backlog>
            <minThreads>5</minThreads>
            <maxThreads>5</maxThreads>
            <status>1</status>
            <properties />
        </listener>
        <listener>
            <host>localhost</host>
            <port>2132</port>
            <backlog>10</backlog>
            <minThreads>5</minThreads>
            <maxThreads>5</maxThreads>
            <status>1</status>
            <properties />
        </listener>
    </listeners>
    <commandPlugins>
        <commandPlugin>
            <checkDelay>3000</checkDelay>
            <class>com.ag.plugin.IdGenerator</class>
            <poolSize>10</poolSize>
            <timeout>10000</timeout>
        </commandPlugin>
    </commandPlugins>
    <servers>
        <connect>
            <status>Unknown</status>
            <threads>8</threads>
            <managementServer>
                <host>localhost</host>
                <port>2242</port>
                <threads>4</threads>
                <timeout>5000</timeout>
            </managementServer>
            <listener>
                <host>localhost</host>
                <port>2232</port>
                <backlog>1000</backlog>
                <minThreads>8</minThreads>
                <maxThreads>8</maxThreads>
                <status>0</status>
                <properties />
            </listener>
        </connect>
        <connect>
            <status>Unknown</status>
            <threads>8</threads>
            <managementServer>
                <host>localhost</host>
                <port>2342</port>
                <threads>4</threads>
                <timeout>5000</timeout>
            </managementServer>
            <listener>
                <host>localhost</host>
                <port>2332</port>
                <backlog>1000</backlog>
                <minThreads>8</minThreads>
                <maxThreads>8</maxThreads>
                <status>0</status>
                <properties />
            </listener>
        </connect>
        <connect>
            <status>Unknown</status>
            <threads>8</threads>
            <managementServer>
                <host>localhost</host>
                <port>2442</port>
                <threads>4</threads>
                <timeout>5000</timeout>
            </managementServer>
            <listener>
                <host>localhost</host>
                <port>2432</port>
                <backlog>1000</backlog>
                <minThreads>8</minThreads>
                <maxThreads>8</maxThreads>
                <status>0</status>
                <properties />
            </listener>
        </connect>
    </servers>
    <clients>
        <connect>
            <status>Unknown</status>
            <threads>8</threads>
            <managementClient>
                <host>localhost</host>
                <port>2042</port>
                <threads>8</threads>
                <timeout>1000</timeout>
            </managementClient>
            <listener>
                <host>localhost</host>
                <port>2132</port>
                <backlog>1000</backlog>
                <minThreads>8</minThreads>
                <maxThreads>8</maxThreads>
                <status>0</status>
                <properties />
            </listener>
        </connect>
    </clients>
    <dataSources>
        <dataSource>
            <name>a</name>
            <class>com.ag.cache.test.userdataaccess.BaseDataInvoker</class>
            <threads>10</threads>
            <timeout>10000</timeout>
            <properties>
                <entry>
                    <key>threads</key>
                    <value>10</value>
                </entry>
                <entry>
                    <key>driver</key>
                    <value>org.hsqldb.jdbcDriver</value>
                </entry>
                <entry>
                    <key>password</key>
                    <value></value>
                </entry>
                <entry>
                    <key>user</key>
                    <value>sa</value>
                </entry>
                <entry>
                    <key>url</key>
                    <value>jdbc:hsqldb:hsql://localhost/test</value>
                </entry>
            </properties>
        </dataSource>
    </dataSources>
    <sessionClients>
        <sessionClient>
            <host>localhost</host>
            <port>5888</port>
            <threads>5</threads>
            <timeout>1000</timeout>
        </sessionClient>
    </sessionClients>
    <calculateStatistic>true</calculateStatistic>
    <saveClients>
        <saveClient>
            <host>localhost</host>
            <port>5824</port>
            <threads>5</threads>
            <timeout>1000</timeout>
        </saveClient>
    </saveClients>
    <saveServers>
        <saveServer>
            <host>localhost</host>
            <port>5824</port>
            <minThreads>25</minThreads>
            <maxThreads>25</maxThreads>
            <keepAliveTime>3000</keepAliveTime>
            <sessionTimeout>1000000</sessionTimeout>
        </saveServer>
    </saveServers>
    <serverName>cacheManager</serverName>
    <sessionServer>
        <host>localhost</host>
        <port>5888</port>
        <minThreads>25</minThreads>
        <maxThreads>25</maxThreads>
        <keepAliveTime>3000</keepAliveTime>
        <sessionTimeLive>18000000</sessionTimeLive>
    </sessionServer>
    <managementServer>
        <host>localhost</host>
        <port>2142</port>
        <minThreads>2</minThreads>
        <maxThreads>12</maxThreads>
        <keepAliveTime>3000</keepAliveTime>
    </managementServer>
</serverModel>
