=== aleksgor/t1/pm/src/main/resources/pm.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ag.com"
	targetNamespace="http://www.ag.com">
	<xs:element name="models" type="models" />
	<xs:complexType name="models">
		<xs:sequence>
			<xs:element type="model" name="model" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="field">
		<xs:sequence>
			<xs:element type="column" name="column" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" />
		<xs:attribute name="primary-key" />
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="string" />
					<xs:enumeration value="byte" />
					<xs:enumeration value="int" />
					<xs:enumeration value="short" />
					<xs:enumeration value="long" />
					<xs:enumeration value="float" />
					<xs:enumeration value="double" />
					<xs:enumeration value="date" />
					<xs:enumeration value="boolean" />
					<xs:enumeration value="binary" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="column">
		<xs:attribute name="name" />
		<xs:attribute name="sql-type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="STRING" />
					<xs:enumeration value="DOUBLE" />
					<xs:enumeration value="DATE" />
					<xs:enumeration value="INT" />
					<xs:enumeration value="LONG" />
					<xs:enumeration value="FLOAT" />
					<xs:enumeration value="CLOB" />
					<xs:enumeration value="BLOB" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="model">
		<xs:sequence>
			<xs:element type="field" name="field" minOccurs="0" maxOccurs="unbounded" />
			<xs:element type="relation" name="relation" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" />
		<xs:attribute name="class" />
		<xs:attribute name="table" />
		<xs:attribute name="identifier" />
	</xs:complexType>

	<xs:complexType name="relation">
		<xs:sequence>
			<xs:element type="relationColumn" name="column" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" />
		<xs:attribute name="relationTo" />
		<xs:attribute name="field" />
		<xs:attribute name="method" />
		<xs:attribute name="join">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="leftOuter" />
					<xs:enumeration value="inner" />
					<xs:enumeration value="rightOuter" />
					<xs:enumeration value="fullOuter" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="relationColumn">
		<xs:attribute name="name" />
		<xs:attribute name="relationTo" />
	</xs:complexType>
</xs:schema>

=== aleksgor/t1/utilities/src/test/resources/model2.xml
<?xml version="1.0"?>
<models xmlns="http://www.ag.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ag.com pm.xsd">
	<model name="MasterModel" class="com.ag.io.model.MasterModel" table="test" identifier="com.ag.io.model.MasterModelId">
		<field name="id" primary-key="true" type="long">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="name2" primary-key="false" type="string">
			<column name="name" sql-type="STRING" />
		</field>
		<field name="date" primary-key="false" type="date">
			<column name="data" sql-type="DATE" />
		</field>
		<field name="childId" primary-key="false" type="long">
			<column name="childId" sql-type="LONG" />
		</field>
		<field name="secondChildId" primary-key="false" type="long">
			<column name="secondChildId" sql-type="LONG" />
		</field>
		<field name="blob" primary-key="false" type="binary">
			<column name="blob" sql-type="BLOB" />
		</field>
		<relation name="rChild" relationTo="Child">
			<column name="childId" relationTo="id" />
		</relation>
		<relation name="sChild" relationTo="Child" field="secondChild">
			<column name="secondChildId" relationTo="id" />
		</relation>

	</model>

	<model name="ChildModel" class="com.ag.io.model.ChildModel" table="child" identifier="com.ag.io.model.ChildModelId">
		<field name="id" primary-key="true" type="long">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="name" primary-key="false" type="string">
			<column name="name" sql-type="CHAR" />
		</field>
	</model>
</models>

=== aleksgor/t1/test/src/test/resources/pm1.cfg.xml
<?xml version="1.0"?>
<!-- xsi:schemaLocation="http://www.ag.com serverModel.xsd" -->
<models xmlns="http://www.ag.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ag.com pm.xsd">
	<model name="Test" class="com.ag.cache.test.model.Test" table="test" identifier="com.ag.cache.test.model.TestId">
		<field name="id" primary-key="true">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="name" primary-key="false">
			<column name="name" sql-type="STRING" />
		</field>
		<field name="date" primary-key="false">
			<column name="data" sql-type="DATE" />
		</field>
		<field name="childId" primary-key="false">
			<column name="childId" sql-type="LONG" />
		</field>
		<relation name="rChild" relationTo="Child">
			<column name="childId" relationTo="id" />
		</relation>
		<field name="money" primary-key="false">
			<column name="money" sql-type="DOUBLE" />
		</field>
		
	</model>

	<model name="Child" class="com.ag.cache.test.model.Child" table="child" identifier="com.ag.cache.test.model.ChildId">
		<field name="id" primary-key="true">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="name" primary-key="false">
			<column name="name" sql-type="STRING" />
		</field>
	</model>
</models>

=== aleksgor/t1/test/src/test/resources/pm.cfg.xml
<?xml version="1.0"?>
<!-- xsi:schemaLocation="http://www.ag.com serverModel.xsd" -->
<models xmlns="http://www.ag.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ag.com pm.xsd">
    <model name="MainTestModel" class="com.ag.cache.test.model.MainTestModel" table="test" identifier="com.ag.cache.test.model.MainTestModelId">
        <field name="id" primary-key="true">
            <column name="id" sql-type="LONG" />
        </field>
        <field name="name" primary-key="false">
            <column name="name" sql-type="STRING" />
        </field>
        <field name="date" primary-key="false">
            <column name="data" sql-type="DATE" />
        </field>
        <field name="childId" primary-key="false">
            <column name="childId" sql-type="LONG" />
        </field>
        <field name="secondChildId" primary-key="false">
            <column name="secondChildId" sql-type="LONG" />
        </field>
        <field name="thirdChildId" primary-key="false">
            <column name="thirdChildId" sql-type="LONG" />
        </field>
        <field name="money" primary-key="false">
            <column name="money" sql-type="DOUBLE" />
        </field>

        <field name="blob" primary-key="false">
            <column name="blobField" sql-type="BLOB" />
        </field>

        <relation name="rChild" relationTo="Child" field="child" join="LEFT_OUTER">
            <column name="childId" relationTo="id" />
        </relation>
        <relation name="sChild" relationTo="Child" field="secondChild" join="LEFT_OUTER">
            <column name="secondChildId" relationTo="id" />
        </relation>
        <relation name="oChild" relationTo="Child" field="thirdChild" join="LEFT_OUTER">
            <column name="id" relationTo="id" />
        </relation>
        <relation name="priceRelation" relationTo="Price" field="prices" join="COLLECTION">
            <column name="id" relationTo="mainId" />
        </relation>
    </model>




    <model name="NoIdTestModel" class="com.ag.cache.test.model.NoIdTestModel" table="test" identifier="com.ag.cache.test.model.NoIdTestModelId">
        <field name="id" primary-key="true">
            <column name="id" sql-type="LONG" />
        </field>
        <field name="name" primary-key="false">
            <column name="name" sql-type="STRING" />
        </field>
        <field name="date" primary-key="false">
            <column name="data" sql-type="DATE" />
        </field>
        <field name="childId" primary-key="false">
            <column name="childId" sql-type="LONG" />
        </field>
        <field name="secondChildId" primary-key="false">
            <column name="secondChildId" sql-type="LONG" />
        </field>
        <field name="thirdChildId" primary-key="false">
            <column name="thirdChildId" sql-type="LONG" />
        </field>
        <field name="money" primary-key="false">
            <column name="money" sql-type="DOUBLE" />
        </field>

        <field name="blob" primary-key="false">
            <column name="blobField" sql-type="BLOB" />
        </field>

        <relation name="rChild" relationTo="Child">
            <column name="childId" relationTo="id" />
        </relation>
        <relation name="sChild" relationTo="Child" field="secondChild">
            <column name="secondChildId" relationTo="id" />
        </relation>
        <relation name="oChild" relationTo="Child" field="thirdChild" join="LEFT_OUTER">
            <column name="id" relationTo="id" />
        </relation>

    </model>
    <model name="Child" class="com.ag.cache.test.model.Child" table="child" identifier="com.ag.cache.test.model.ChildId">
        <field name="id" primary-key="true">
            <column name="id" sql-type="LONG" />
        </field>
        <field name="name" primary-key="false">
            <column name="name" sql-type="CHAR" />
        </field>
    </model>
    
    <model name="Price" class="com.ag.cache.test.model.Price" table="price" identifier="com.ag.cache.test.model.PriceId">
        <field name="id" primary-key="true">
            <column name="id" sql-type="LONG" />
        </field>
        <field name="mainId" primary-key="false">
            <column name="mainId" sql-type="LONG" />
        </field>
        <field name="name" primary-key="false">
            <column name="name" sql-type="CHAR" />
        </field>
        <field name="startDate" primary-key="false">
            <column name="startDate" sql-type="DATE" />
        </field>
        <field name="endDate" primary-key="false">
            <column name="endDate" sql-type="DATE" />
        </field>
        <field name="money" primary-key="false">
            <column name="money" sql-type="DOUBLE" />
        </field>
        <field name="valuta" primary-key="false">
            <column name="valuta" sql-type="CHAR" />
        </field>

    </model>

</models>

=== aleksgor/t1/pm/src/test/resources/pm.cfg.xml
<?xml version="1.0"?>
<!-- xsi:schemaLocation="http://www.ag.com serverModel.xsd" -->
<models xmlns="http://www.ag.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ag.com pm.xsd">
	<model name="Test" class="com.ag.pm.test.models.MainClass" table="test" identifier="com.ag.pm.test.models.TestId">
		<field name="mainId" primary-key="true">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="mainName" primary-key="false">
			<column name="name" sql-type="STRING" />
		</field>
		<field name="mainDate" primary-key="false">
			<column name="data" sql-type="DATE" />
		</field>
		<field name="childId" primary-key="false">
			<column name="childId" sql-type="LONG" />
		</field>
		<field name="secondChildId" primary-key="false">
			<column name="secondChildId" sql-type="LONG" />
		</field>
		<field name="blob" primary-key="false">
			<column name="blobField" sql-type="BLOB" />
		</field>

		<relation name="rChild" relationTo="Child">
			<column name="childId" relationTo="id" />
		</relation>
		<relation name="sChild" relationTo="Child" field="secondChild">
			<column name="secondChildId" relationTo="id" />
		</relation>
		<relation name="oChild" relationTo="Child" field="thirdChild" join="LEFT_OUTER">
			<column name="mainId" relationTo="id" />
		</relation>

	</model>
	<model name="Child" class="com.ag.pm.test.models.Child" table="child" identifier="com.ag.pm.test.models.ChildId">
		<field name="id" primary-key="true">
			<column name="id" sql-type="LONG" />
		</field>
		<field name="name" primary-key="false">
			<column name="name" sql-type="CHAR" />
		</field>
	</model>
</models>
